"""
Company configuration.

method values:
  "workday"  -> real scrape via Workday's CXS JSON API (reliable, confirmed working pattern)
  "google" / "microsoft" / "apple" / "amazon" -> real scrape via each company's own
              internal JSON endpoint (best-effort; unofficial/undocumented, can change)
  "fallback" -> no scrapeable API found (login-gated, GraphQL, or full JS SPA).
              We generate a direct search link into their career portal instead of
              pretending to scrape it.

Search terms used to query each source live in keywords.py (SEARCH_TERMS).
"""

COMPANIES = [
    # ---------- IT / Tech / Software MNCs ----------
    {"name": "TCS", "category": "IT / Tech", "method": "fallback", "url": "https://ibegin.tcs.com/iBegin/jobs/search?q={query}"},
    {"name": "Infosys", "category": "IT / Tech", "method": "fallback", "url": "https://career.infosys.com/joblist"},
    {"name": "Wipro", "category": "IT / Tech", "method": "fallback", "url": "https://careers.wipro.com/careers-home/jobs?keywords={query}"},
    {"name": "Tech Mahindra", "category": "IT / Tech", "method": "fallback", "url": "https://careers.techmahindra.com/"},
    {"name": "HCLTech", "category": "IT / Tech", "method": "fallback", "url": "https://www.hcltech.com/careers/Careers-in-india"},
    {"name": "Cognizant", "category": "IT / Tech", "method": "fallback", "url": "https://careers.cognizant.com/global/en/search-results?keywords={query}"},
    {"name": "Accenture", "category": "IT / Tech", "method": "fallback", "url": "https://www.accenture.com/in-en/careers/jobsearch?jk={query}"},
    {"name": "Capgemini", "category": "IT / Tech", "method": "fallback", "url": "https://www.capgemini.com/in-en/careers/job-search/?keyword={query}"},
    {"name": "Deloitte", "category": "IT / Tech", "method": "fallback", "url": "https://jobs2.deloitte.com/ui/en/search-results?q={query}"},
    {"name": "Microsoft", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.careers.microsoft.com/global/en/search?q={query}&l=en_us"},
    {"name": "Google", "category": "IT / Tech", "method": "fallback", "url": "https://www.google.com/about/careers/applications/jobs/results/?q={query}"},
    {"name": "Amazon", "category": "IT / Tech", "method": "fallback", "url": "https://www.amazon.jobs/en/search?base_query={query}"},
    {"name": "Apple Inc.", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.apple.com/en-us/search?search-term={query}"},
    {"name": "Cisco", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.cisco.com/jobs/SearchJobs/?&q={query}"},
    {"name": "IBM", "category": "IT / Tech", "method": "fallback", "url": "https://www.ibm.com/careers/search?q={query}"},
    {"name": "Oracle", "category": "IT / Tech", "method": "fallback", "url": "https://careers.oracle.com/en/sites/jobsearch/jobs?keyword={query}"},
    {"name": "Meta Platforms", "category": "IT / Tech", "method": "fallback", "url": "https://www.metacareers.com/jobs/?q={query}"},
    {"name": "Adobe", "category": "IT / Tech", "method": "fallback", "url": "https://careers.adobe.com/us/en/search-results?keywords={query}"},
    {"name": "Intel", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.intel.com/en/search-jobs/{query}"},
    {"name": "NVIDIA", "category": "IT / Tech", "method": "fallback", "url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q={query}"},
    {"name": "Salesforce", "category": "IT / Tech", "method": "fallback", "url": "https://careers.salesforce.com/en/jobs/?search={query}"},
    {"name": "PayPal", "category": "IT / Tech", "method": "fallback", "url": "https://careers.paypal.com/global/en/search-results?keywords={query}"},
    {"name": "Visa", "category": "IT / Tech", "method": "fallback", "url": "https://search.visa.com/job-search-results?keyword={query}"},
    {"name": "Mastercard", "category": "IT / Tech", "method": "fallback", "url": "https://careers.mastercard.com/us/en/search-results?keywords={query}"},
    {"name": "NetApp", "category": "IT / Tech", "method": "fallback", "url": "https://careers.netapp.com/search-jobs?k={query}"},
    {"name": "VMware / Broadcom", "category": "IT / Tech", "method": "fallback", "url": "https://careers.broadcom.com/search-jobs?k={query}"},
    {"name": "Dell", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.dell.com/search-jobs?k={query}"},
    {"name": "HP", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.hp.com/search-jobs?k={query}"},
    {"name": "Lenovo", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.lenovo.com/en_US/careers/SearchJobs/?keyword={query}"},
    {"name": "Atlassian", "category": "IT / Tech", "method": "fallback", "url": "https://www.atlassian.com/company/careers"},
    {"name": "Intuit", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.intuit.com/search-jobs?k={query}"},
    {"name": "ServiceNow", "category": "IT / Tech", "method": "fallback", "url": "https://careers.servicenow.com/careers/jobs?keyword={query}"},
    {"name": "SAP", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.sap.com/search/?q={query}"},
    {"name": "Micron", "category": "IT / Tech", "method": "fallback", "url": "https://jobs.micron.com/search/?q={query}"},
    {"name": "Texas Instruments", "category": "IT / Tech", "method": "fallback", "url": "https://careers.ti.com/search-jobs/?k={query}"},
    {"name": "AMD", "category": "IT / Tech", "method": "fallback", "url": "https://careers.amd.com/careers-home/jobs?keywords={query}"},
    {"name": "Western Digital", "category": "IT / Tech", "method": "fallback", "url": "https://careers.westerndigital.com/jobs/search?q={query}"},

    # ---------- Automotive & Manufacturing ----------
    {"name": "Maruti Suzuki", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.marutisuzuki.com/corporate/careers"},
    {"name": "Hyundai Motor India", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.hyundai.com/in/en/about-us/careers"},
    {"name": "Toyota", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.toyotabharat.com/careers/"},
    {"name": "Tata Motors", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.tatamotors.com/careers/"},
    {"name": "Mahindra", "category": "Automotive / Mfg", "method": "fallback", "url": "https://jobs.mahindra.com/"},
    {"name": "Ather Energy", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.atherenergy.com/careers"},
    {"name": "Ola Electric", "category": "Automotive / Mfg", "method": "fallback", "url": "https://olaelectric.com/careers"},
    {"name": "TVS Motor", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.tvsmotor.com/careers"},
    {"name": "Bajaj Auto", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.bajajauto.com/careers"},
    {"name": "Hero MotoCorp", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.heromotocorp.com/en-in/careers.html"},
    {"name": "Renault Nissan", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.rnti.co.in/careers"},
    {"name": "Ford", "category": "Automotive / Mfg", "method": "fallback", "url": "https://corporate.ford.com/careers.html"},
    {"name": "General Motors", "category": "Automotive / Mfg", "method": "fallback", "url": "https://search-careers.gm.com/jobs/search?q={query}"},
    {"name": "Stellantis", "category": "Automotive / Mfg", "method": "fallback", "url": "https://careers.stellantis.com/global/en/search-results?keywords={query}"},
    {"name": "Volvo", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.volvogroup.com/en/careers/job-search.html?q={query}"},
    {"name": "Daimler", "category": "Automotive / Mfg", "method": "fallback", "url": "https://jobs.daimlertruck.com/"},
    {"name": "BMW", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.bmwgroup.jobs/in/en.html"},
    {"name": "Boeing", "category": "Automotive / Mfg", "method": "fallback", "url": "https://jobs.boeing.com/search-jobs?k={query}"},
    {"name": "Airbus", "category": "Automotive / Mfg", "method": "fallback", "url": "https://ag.wd3.myworkdayjobs.com/Airbus?q={query}"},
    {"name": "Lockheed Martin", "category": "Automotive / Mfg", "method": "fallback", "url": "https://www.lockheedmartinjobs.com/search-jobs/{query}"},
    {"name": "Rolls-Royce", "category": "Automotive / Mfg", "method": "fallback", "url": "https://careers.rolls-royce.com/"},

    # ---------- BFSI / Finance / GCC ----------
    {"name": "Wells Fargo", "category": "BFSI / Finance", "method": "fallback", "url": "https://www.wellsfargojobs.com/en/jobs/?search={query}&location=India"},
    {"name": "JPMorgan Chase", "category": "BFSI / Finance", "method": "fallback", "url": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/requisitions?keyword={query}"},
    {"name": "Goldman Sachs", "category": "BFSI / Finance", "method": "fallback", "url": "https://careers.gs.com/jobs?keyword={query}"},
    {"name": "HDFC Bank", "category": "BFSI / Finance", "method": "fallback", "url": "https://hdfcbank.careers.zwayam.com/job-search"},
    {"name": "ICICI Bank", "category": "BFSI / Finance", "method": "fallback", "url": "https://www.icicicareers.com/Careers/JobSearch.aspx"},
    {"name": "Barclays", "category": "BFSI / Finance", "method": "fallback", "url": "https://search.jobs.barclays/job-search-results?keyword={query}"},
    {"name": "Citi", "category": "BFSI / Finance", "method": "fallback", "url": "https://jobs.citi.com/search-jobs?k={query}"},
    {"name": "Standard Chartered", "category": "BFSI / Finance", "method": "fallback", "url": "https://sc.taleo.net/careersection/sc1/jobsearch.ftl?keyword={query}"},
    {"name": "KPMG", "category": "BFSI / Finance", "method": "fallback", "url": "https://home.kpmg/in/en/home/careers.html"},
    {"name": "EY", "category": "BFSI / Finance", "method": "fallback", "url": "https://careers.ey.com/ey/search/?q={query}"},
    {"name": "Bain & Company", "category": "BFSI / Finance", "method": "fallback", "url": "https://www.bain.com/careers/"},
    {"name": "McKinsey", "category": "BFSI / Finance", "method": "fallback", "url": "https://www.mckinsey.com/careers/search-jobs?q={query}"},
    {"name": "BCG", "category": "BFSI / Finance", "method": "fallback", "url": "https://careers.bcg.com/search-results?keywords={query}"},
    {"name": "Morgan Stanley", "category": "BFSI / Finance", "method": "fallback", "url": "https://ms.taleo.net/careersection/2/jobsearch.ftl?keyword={query}"},
    {"name": "Fidelity", "category": "BFSI / Finance", "method": "fallback", "url": "https://jobs.fidelity.com/search-jobs/?k={query}"},
    {"name": "Bank of America", "category": "BFSI / Finance", "method": "fallback", "url": "https://careers.bankofamerica.com/en-us/job-search?search={query}"},
    {"name": "DE Shaw", "category": "BFSI / Finance", "method": "fallback", "url": "https://www.deshaw.com/careers"},
    {"name": "FactSet", "category": "BFSI / Finance", "method": "fallback", "url": "https://factset.wd1.myworkdayjobs.com/FactSetCareers"},
    {"name": "American Express", "category": "BFSI / Finance", "method": "fallback", "url": "https://aexp.eightfold.ai/careers?query={query}"},

    # ---------- Other Prominent MNCs ----------
    {"name": "Samsung", "category": "Other Prominent", "method": "fallback", "url": "https://www.samsung.com/in/about-us/careers/"},
    {"name": "Reliance Industries / Jio", "category": "Other Prominent", "method": "fallback", "url": "https://careers.jio.com/frmjobsearch.aspx"},
    {"name": "Flipkart (Walmart)", "category": "Other Prominent", "method": "fallback", "url": "https://www.flipkartcareers.com/"},
    {"name": "Qualcomm", "category": "Other Prominent", "method": "fallback", "url": "https://careers.qualcomm.com/careers/search-jobs?keywords={query}"},
    {"name": "Bosch", "category": "Other Prominent", "method": "fallback", "url": "https://careers.smartrecruiters.com/BoschGroup/india"},
    {"name": "Siemens", "category": "Other Prominent", "method": "fallback", "url": "https://jobs.siemens.com/careers?query={query}"},
    {"name": "Schneider Electric", "category": "Other Prominent", "method": "fallback", "url": "https://careers.se.com/global/jobs?keyword={query}"},
    {"name": "P&G", "category": "Other Prominent", "method": "fallback", "url": "https://www.pgcareers.com/global/en/search-results?keywords={query}"},
    {"name": "HUL", "category": "Other Prominent", "method": "fallback", "url": "https://careers.unilever.com/india"},
    {"name": "Nestlé", "category": "Other Prominent", "method": "fallback", "url": "https://www.nestle.in/jobs/search-jobs?keyword={query}"},
    {"name": "Swiggy", "category": "Other Prominent", "method": "fallback", "url": "https://careers.swiggy.com/"},
    {"name": "Zomato", "category": "Other Prominent", "method": "fallback", "url": "https://www.zomato.com/careers"},
    {"name": "Ola", "category": "Other Prominent", "method": "fallback", "url": "https://www.olacabs.com/careers"},
    {"name": "Uber", "category": "Other Prominent", "method": "fallback", "url": "https://www.uber.com/global/en/careers/list/?query={query}"},
    {"name": "Airbnb", "category": "Other Prominent", "method": "fallback", "url": "https://careers.airbnb.com/positions/?q={query}"},
    {"name": "Expedia", "category": "Other Prominent", "method": "fallback", "url": "https://careers.expediagroup.com/jobs/?search={query}"},
    {"name": "MakeMyTrip", "category": "Other Prominent", "method": "fallback", "url": "https://careers.makemytrip.com/"},
    {"name": "PhonePe", "category": "Other Prominent", "method": "fallback", "url": "https://www.phonepe.com/careers/"},
    {"name": "Paytm", "category": "Other Prominent", "method": "fallback", "url": "https://paytm.com/careers/"},
    {"name": "Cred", "category": "Other Prominent", "method": "fallback", "url": "https://careers.cred.club/"},
    {"name": "Meesho", "category": "Other Prominent", "method": "fallback", "url": "https://meesho.io/jobs"},
    {"name": "Razorpay", "category": "Other Prominent", "method": "fallback", "url": "https://razorpay.com/jobs/"},
    {"name": "ShareChat", "category": "Other Prominent", "method": "fallback", "url": "https://sharechat.com/careers"},
    {"name": "Dream11", "category": "Other Prominent", "method": "fallback", "url": "https://www.dream11.com/careers"},
    {"name": "Groww", "category": "Other Prominent", "method": "fallback", "url": "https://groww.in/careers"},
    {"name": "Zerodha", "category": "Other Prominent", "method": "fallback", "url": "https://zerodha.com/careers/"},
    {"name": "InMobi", "category": "Other Prominent", "method": "fallback", "url": "https://www.inmobi.com/company/careers/"},
    {"name": "BrowserStack", "category": "Other Prominent", "method": "fallback", "url": "https://www.browserstack.com/careers"},
    {"name": "Postman", "category": "Other Prominent", "method": "fallback", "url": "https://www.postman.com/company/careers/"},
    {"name": "Druva", "category": "Other Prominent", "method": "fallback", "url": "https://www.druva.com/about/careers"},

    # ---------- Additional IT/Services/Engineering ----------
    {"name": "Persistent Systems", "category": "Additional IT/Services", "method": "fallback", "url": "https://careers.persistent.com/"},
    {"name": "LTI Mindtree", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.ltimindtree.com/careers/"},
    {"name": "Mphasis", "category": "Additional IT/Services", "method": "fallback", "url": "https://careers.mphasis.com/home/jobs.html"},
    {"name": "NTT Data", "category": "Additional IT/Services", "method": "fallback", "url": "https://careers.nttdata.com/search/?q={query}"},
    {"name": "DXC", "category": "Additional IT/Services", "method": "fallback", "url": "https://careers.dxc.com/global/en/search-results?keywords={query}"},
    {"name": "Virtusa", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.virtusa.com/careers/search"},
    {"name": "Hexaware", "category": "Additional IT/Services", "method": "fallback", "url": "https://jobs.hexaware.com/"},
    {"name": "Zensar", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.zensar.com/careers"},
    {"name": "ThoughtWorks", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.thoughtworks.com/careers/jobs"},
    {"name": "Freshworks", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.freshworks.com/company/careers/"},
    {"name": "GE", "category": "Additional IT/Services", "method": "fallback", "url": "https://jobs.gecareers.com/global/en/search-results?keywords={query}"},
    {"name": "Honeywell", "category": "Additional IT/Services", "method": "fallback", "url": "https://careers.honeywell.com/us/en/search-results?keywords={query}"},
    {"name": "Eaton", "category": "Additional IT/Services", "method": "fallback", "url": "https://jobs.eaton.com/jobs?keywords={query}"},
    {"name": "3M", "category": "Additional IT/Services", "method": "fallback", "url": "https://3m.wd1.myworkdayjobs.com/Search?q={query}"},
    {"name": "Mindtree", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.mindtree.com/careers"},
    {"name": "L&T Technology Services", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.ltts.com/careers"},
    {"name": "Mu Sigma", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.mu-sigma.com/careers"},
    {"name": "ZS Associates", "category": "Additional IT/Services", "method": "fallback", "url": "https://jobs.zs.com/search/?q={query}"},
    {"name": "CGI", "category": "Additional IT/Services", "method": "fallback", "url": "https://cgi.njoyn.com/corp/xweb/xweb.asp?page=joblisting"},
    {"name": "Genpact", "category": "Additional IT/Services", "method": "fallback", "url": "https://careers.genpact.com/global/en/search-results?keywords={query}"},
    {"name": "CitiusTech", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.citiustech.com/careers"},
    {"name": "Tiger Analytics", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.tigeranalytics.com/careers/"},
    {"name": "LatentView", "category": "Additional IT/Services", "method": "fallback", "url": "https://www.latentview.com/careers/"},
]
